apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "svcname" . }}-data
  namespace: smartdispatch
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.global.storageClass | default "standard" }}
  resources:
    requests:
      storage: 500Mi