apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: smartdispatch
data:
  KAFKA_BOOTSTRAP: {{ .Values.global.kafkaBootstrap | default "smartdispatch-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092" | quote }}
  MATCHER: {{ .Values.matcher | default "nearest" | quote }}
  DB_PATH: "/data/db.sqlite"
  SERVICE_PORT: {{ .Values.port | toString | quote }}